project:
  type: website
  render:
    - "*.qmd"
    - "!admin/"

website:
  open-graph: true
  title: "Evaluation & responsibility in infectious disease modelling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 2026-03-24.qmd
        text: Schedule
      - href: register.qmd
        text: Join us

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

